### ISSUE TITLE
Error with metadata

### ISSUE THREAD

**Issue by contactalexliu** [christophercliff/heroku-stripe-checkout#2]
When testing the Stripe Checkout platform with Heroku, the app always spits out this line:

{"statusCode":400,"error":"Bad Request","message":"child \"metadata\" fails because [metadata must be an object]","validation":{"source":"payload","keys":["metadata"]}}

I've already tried removing all instances of "metadata" from the app, but this error still shows. What should I do?

**Comment by contactalexliu** [comment]
Never mind, I've fixed it :P

**Comment by michaelflux** [comment]
@contactalexliu what was the fix? I'm experiencing the same problem.

**Comment by contactalexliu** [comment]
View my forked version of the app. Also, remove the metadata line:

(<input name="metadata" value="YOUR_METADATA" type="hidden">)

from your HTML code.

Set up your app using this forked repo:
https://github.com/authinking/heroku-stripe-checkout

The above version has all metadata settings removed. That fixed it for me.

**Comment by michaelflux** [comment]
Beautiful. Thanks @contactalexliu   No longer produces any errors - though for some reason every time I try doing a test transaction using Stripe's test card numbers, I get bounced to the failed url.  Any chance you would have any tips for that? :p

**Comment by contactalexliu** [comment]
Have you properly set a "success" page or "failed" page yet? I am sorry,
but since I am not experiencing these issues I can't be of much help here.
Try rebuilding the app; it might fix the problem.

**Comment by michaelflux** [comment]
Yeah, set the success and failed pages.  :p Oh well, will follow up with Stripe itself as all is being passed on to them without any issues.

Cheers,
m

**Comment by christophercliff** [comment]
The metadata field is optional, just remove the `<input>` tag from your markup. If you want to include metadata, `YOUR_METADATA` must be a JavaScript object, JSON stringified and HTML encoded.

**Comment by landestates** [comment]
christophercliff, please give an example of a valid value that is a JavaScript object, JSON stringify and HTML encoded. ty

**Comment by christophercliff** [comment]
`value` must be a stringified object rather than a plain object. So the output of `JSON.stringify({ product_id: '12345' })`.

Also, a reminder that this project has been deprecated in favor of https://github.com/christophercliff/flatmarket-server-heroku.
