### ISSUE TITLE
Add support for shipping/billing addresses

### ISSUE THREAD

**Issue by michaelflux** [christophercliff/heroku-stripe-checkout#3]
Including additional Stripe options during checkout such as `data-billingAddress="true"` and `data-shippingAddress="true"`, results in the following error when the data is passed on to the Heroku server.

`{"statusCode":400,"error":"Bad Request","message":"\"stripeBillingName\" is not allowed. \"stripeBillingAddressLine1\" is not allowed. \"stripeBillingAddressZip\" is not allowed. \"stripeBillingAddressState\" is not allowed. \"stripeBillingAddressCity\" is not allowed. \"stripeBillingAddressCountry\" is not allowed. \"stripeBillingAddressCountryCode\" is not allowed. \"stripeShippingName\" is not allowed. \"stripeShippingAddressLine1\" is not allowed. \"stripeShippingAddressZip\" is not allowed. \"stripeShippingAddressState\" is not allowed. \"stripeShippingAddressCity\" is not allowed. \"stripeShippingAddressCountry\" is not allowed. \"stripeShippingAddressCountryCode\" is not allowed","validation":{"source":"payload","keys":["stripeBillingName","stripeBillingAddressLine1","stripeBillingAddressZip","stripeBillingAddressState","stripeBillingAddressCity","stripeBillingAddressCountry","stripeBillingAddressCountryCode","stripeShippingName","stripeShippingAddressLine1","stripeShippingAddressZip","stripeShippingAddressState","stripeShippingAddressCity","stripeShippingAddressCountry","stripeShippingAddressCountryCode"]}}`

The data that was input into the Address fields, does get passed onto Stripe and does appear as expected in the logs, however the transaction does not succeed as it halts at the Heroku server.

What would be the correct way of adding the additional input fields to the form that gets passed onto Heroku that would cause a successful transaction?

**Comment by christophercliff** [comment]
I think this is just a matter of updating the payload validation to include all possible fields from Stripe: https://github.com/christophercliff/heroku-stripe-checkout/blob/ff1838733c5e1c99b4aa696e4d95b014177839b0/lib/server.js#L41-L46

**Comment by christophercliff** [comment]
See https://json.expert/flatmarket/.

**Comment by lejacobroy** [comment]
Same problem, is there a way to fix it?
I tried to add the fields to the validation process, but I can't figure out how..

I have a lot of products already in my Jekyll front-end, so I can't use flatmarket.
I also need the items to be shipped, that's why I need the shipping/billing address.

Thank you.

**Comment by lejacobroy** [comment]
After a good night of sleep and some coffee in the morning, here's the way that I made it work :

First, change the bits highlighted in @christophercliff 's comment so it looks like this :

            payload: {
                amount: Joi.number().integer().greater(50).required(),
                description: Joi.string(),
                metadata: Joi.object(),
                stripeToken: Joi.string().token().required(),
                stripeTokenType: Joi.string().regex(/^card$/),
                stripeEmail: Joi.string().email().required(),
				stripeBillingName: Joi.string(),
				stripeBillingAddressLine1: Joi.string(),
				stripeBillingAddressZip: Joi.string(),
				stripeBillingAddressState: Joi.string(),
				stripeBillingAddressCity: Joi.string(),
				stripeBillingAddressCountry: Joi.string(),
				stripeBillingAddressCountryCode: Joi.string(),
				stripeShippingName: Joi.string(),
				stripeShippingAddressLine1: Joi.string(),
				stripeShippingAddressZip: Joi.string(),
				stripeShippingAddressState: Joi.string(),
				stripeShippingAddressCity: Joi.string(),
				stripeShippingAddressCountry: Joi.string(),
				stripeShippingAddressCountryCode: Joi.string(),

            },

I think it just accept to parse the infos as string, or something like that.

Also, as of today (26 oct 2015) the Stripe Api has changed, and the correct way to call the charge is like this :

        var options = {
            amount: request.payload.amount,
            currency: config.currency,
            source: request.payload.stripeToken,
            description: request.payload.description,
        }

(change card: for source: and remove the buyer_email, I replaced it with description).

Hope it helps someone!

**Comment by christophercliff** [comment]
[Flatmarket](https://github.com/christophercliff/flatmarket) now supports billing and shipping addresses. 

The Hapi route configuration is here if you're interested in rolling your own:

https://github.com/christophercliff/hapi-flatmarket/blob/b9145e407926561f5ae092722961de675b173a89/lib/index.js#L35-L120
